### ISSUE TITLE
FR: focus point x and y values

### ISSUE THREAD

**Issue by johanneslamers** [roundhouse/focuspoint#2]
Would love to use this in combination with Imager to specify the crop of the image.
But then I need separate X and Y percentage values. A bit like this Craft Plugin https://github.com/smcyr/Craft-FocusPoint .. but I like your UI much much more. 
````
{% set image = entry.image.first() %}
{% set transformedImage = craft.imager.transformImage(image, {
    width: 800,
    mode: 'crop',
    position: image.photoFocalPoint.x ~ '% ' ~ image.photoFocalPoint.y ~ '%'
}) %}
<img src="{{ transformedImage.url }}">
````

**Comment by johanneslamers** [comment]
or maybe simpler.. remove / disable "background-position" output with some sort of tag.

**Comment by owldesign** [comment]
@johanneslamers so this is already implemented I just haven't showed any documentations :( .. I'll update readme with some code this afternoon. Thanks.

**Comment by owldesign** [comment]
@johanneslamers I updated readme with some usage examples, let me know if that worked out for you.
