### ISSUE TITLE
Not able to set asset source

### ISSUE THREAD

**Issue by alexcarpenter** [roundhouse/focuspoint#3]
Using focuspoint on a new Craft site version  2.6.2962, and I am not able to set a asset source when making use of the focuspoint fieldtype.

This is all I get:

![screen shot 2017-02-23 at 12 36 36 pm](https://cloud.githubusercontent.com/assets/825855/23271229/bdab7a84-f9c4-11e6-8f56-122691e4998e.jpg)

**Comment by owldesign** [comment]
@alexcarpenter to use the field you must attach it to the asset source it self.

Go to your asset source and click `Field Layout` tab, here you will need to add that focuspoint fieldtype you created. 

There are some gif instructions you can see after you install the plugin that might help.. see `yoursite.com/admin/focuspoint/welcome` 

Let me know if you are still stuck!
